.TH systemd\ hints 7 2022-05-17
.
.\" ==========================================================
.SH NAME
.\" ==========================================================
.PP
.B systemd_hints
\(em Short, but growing list of useful systemd advice
.
.\" ==========================================================
.SH SYNOPSIS
.\" ==========================================================
.SS INTRODUCTION
.PP
There is a lot to learn about using
.B systemd
on the modern Linux system.
.PP
This document only tries to direct the reader towards the
locations of certain important files and
.B man
pages.
.SS THE HINTS
.TP
.B SystemD Script Files location
/usr/lib/systemd/system
