.TH groff_hints 7 2022-05-06
.
.\" ==========================================================
.SH NAME
.\" ==========================================================
.B Groff Hints
\(em Little things that make writing roff documents easier
.
.\" ==========================================================
.SH DESCRIPTION
.\" ==========================================================
.PP
Writing
.B man
pages, in particular, is not so much hard as it is enigmatic.
There are some tools and processes that can make it much easier.
This document hopes to provide a useful collection of these
hints.
.
.\" ==========================================================
.SH EXAMPLES
.\" ==========================================================
.SS Editing Hints
.PP
I write code primarily the
.B Emacs
editor.
.B Emacs is well-suited for creating
.B man
and other roff pages.  Here are some things that have helped me.
.\" ============
.TP
.BR "Use Emacs major-mode nroff" :
.br
.B Emacs
may not recognize your document as a roff document, resulting in
your editing being done in
.I Fundamental
mode.  Explicitely call for
.B man
page editing mode with:
.EX
.BI "M-x " nroff-mode
.EE

.\" ============
.TP
.B View nroff-mode help
.br
This advice applies to any
.Emacs
major mode, once you're in the appropriate mode, learn or review
the mode's features by looking at its help page:
.EX
.B C-h m
.EE
.\" --------------------------
.TP
.B Activate \*(lqnroff\*(rq mode
.br
Get a previous of how your man page will be formatted by opening a
.BR nroff-view .
.EX
.B C-c C-c
.EE
.RE
.\" ===============================
.SS Markup Hints
.PP
There is a modest collection of
.B man page
macros, not enough to do everything an author might want.
It is useful to become familiar with the
.I groff language
and its references,
.BR groff "(7) and " "info groff" .
.PP
This subsection will present
.I groff language
solutions to a few formatting challenges to demonstrate how
one might do their own search.
.\"-------------------
.TP
.B Non-breaking words
I find it pretty ugly when a command word is hyphenated on a
.IR "man page" .
An online search was no help for avoiding it, so I looked to
.BR groff (7),
searching for \(lqhyphenation\(rq.
.PP
.RS
It turns out that there are hyphenation levels, with hyphenation
level 1 being the default.
I choose to exploit this feature to prevent a word break by
temporarily disabling hyphenation.
Look at the following code to prevent the hyphenation of
.IR iptables :
.PP
.EX
    .hy 0
    iptables
    .hy 1
.EE
.RE


