.TH FIREWALL\ TIPS 7 2022-05-13
.
.\" ---------------- this about-to-start section, up high for editing, goes below when done:
.\" ---------------- this just-finished sectiongoes below when done:


.\" ==========================================================
.SH NAME
.\" ==========================================================
.B firewall_tips
\(em Tips to help you past unexpected, obscurely-documented firewall setup
.
.\" ==========================================================
.SH DESCRIPTION
.\" ==========================================================
.PP
This is a guide to building a gateway router, combining a
dhcp server using
.B isc-dhcp-server
and a firewall using
.B iptables
.PP
The functions of
.IR dhcp " and " firewall
are related.   The dhcp server identifies users by MAC address and
host names, and the firewall grants or denies access according to
users' identities as defined by their IP address.
.
.\" ==========================================================
.SH SETUP
.\" ==========================================================
.NP
This guide assumes that both
.IR isc-dhcp-server " and " iptables
software are installed.
.\"
.\" ---------------------
.SS HARDWARE REQUIREMENTS
.PP
Any type of router requires at least two network interface cards
.RI ( NIC ).
A firewall router should have interfaces that are at least as fast
as the data delivery speed of the network to which they are attached.
.\"
.\" ---------------------
.SS SOFTWARE CONFIGURATION
.PP
These are the steps for successfully implementing a simple firewall/
dhcp server:
.PP
.B \(bu NIC CONFIGURATION
.RS 4
.PP
The internet facing NIC is often configured by an internet service
provider
.RI ( ISP ).
The LAN-facing NIC needs to have a static IP address.
See the
.B NIC CONFIGURATION DISCUSSION
below to learn about some of the ways this can be done.
.RE
.PP
.B \(bu DHCP SETUP
.RS 4
.PP
The DHCP server provides various IP addresses to enable clients to
configure their NICs without network conflicts.  There are a few files
that require attention to enable the DHCP service.
.TP 4
.B /etc/dhcp/dhcpd.conf
to configure how the dhpc server provides network access values.
.BR dhcpd.conf (5)
.TP 4
.B /var/lib/dhcp/dhcpd.leases
to keep track of to whom certain IP resources are allocated.
This
file must be created (use
.BR touch )
if it the dhcp-server setup hasn't already created it.
.BR dhcpd.leases (5)
.TP 4
.B /etc/default/isc-dhcp-server
must be edited to inform the dhcp-server which NIC to monitor for
DHCP-requests.
Installing
.B isc-dhcp-server
installs this configuration file.  The file contains information on
how to modify it.
.RE
.PP
.B \(bu FIREWALL SETUP
.RS 4
.PP
Write an
.B iptables
script to define rules for network address translation
.RB ( NAT )
and blocking potentially unfriendly access from the internet.
.PP
Configure
.B iptables
logging to redirect messages to an iptables-specific file.
.PP
See
.B BREAK-OUT FIREWALL LOG MESSAGES
below.
.RE
.\"=============================
.SS NIC CONFIGURATION DISCUSSION
.PP
At least one of the NICs must be configured as a static address for
a successful gateway computer.
Unfortunately, different platforms use
different methods, and sometimes change them from version to version.
This discussion will show three different methods, two relatively recent
styles using SystemD, and a legacy style using /etc/init.d.
.\" ----------------------------
.TP 4
.B SystemD.netplan
Internet interfaces are configured using netplan under
systemd.
The following listing is a very simple but complete netplan
configuration file, with
.B eth0
facing the internet and
.B eth0
facing the LAN:
.PP
.RS 4
.RS 4
.EX
# /etc/netplan/00-installer-config.yaml
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
    eth1:
      addresses:
      - 192.168.0.32
.EE
.RE
.PP
 See man page
.BR netplan (5).
.RE
.\" ----------------------------
.TP 4
.B SystemD.network
Using the
.B network
service under the control of
.B systemd
uses files under the directory
.B /etc/systemd/network
that use the INI-style configuration, with sections in square braces
followed by lines of key-value pairs separated with an equals
character.
.RS 4
.RS 4
.PP
.EX
# /etc/systemd/network/50-local.network
[Match]
Name=eth0
[Network]
DHCP=yes

[Match]
Name=eth1
[Network]
Address=192.168.0.32/24
Gateway=192.168.0.32
.EE
.RE
See man page
.BR systemd.network (5).
.RE
.\" ----------------------------
.TP 4
.B Legacy SystemV
Despite systemd running some things on a RaspberryPi, the network
configuration is done with SystemV /etc/network/interfaces.
An administrator can enter the code directly into
/etc/network/interfaces, or create per-NIC configuration files in the
/etc/network/interfaces.d directory.
.RS 4
.PP
The following listing would be in /etc/network/interfaces to show
both the dhcp and static versions:
.RS 4
.PP
.EX
# /etc/network/interfaces
auto eth0
iface eth0 inet dhcp

auto eth1
iface eth1 inet static
  address 192.168.0.32
  netmask 255.255.255.0
  broadcast 192.168.0.255
.EE
.RE
.PP
See also man page
.IR interfaces (5).
.RE
.\"================================
.SS BREAK-OUT FIREWALL LOG MESSAGES
.PP
Sometimes iptables will log a large volume of messages.
It can overwhelm regular system messages, making it hard to
diagnose other problems.
This subsection demonstrates how to configure a system to save
iptables log messages to a separate file.
.PP
This is a two-step process.
The first step is to prepare a filter, using
.BR rsyslog ,
based on a log message, and the second step is to include that
filter string in iptable log messages.
.TP 4
.B Filtering iptables Messages
In directory
.BR /etc/rsyslog.d ,
create a file, something like
.hy 0
.BR 10\-iptables.conf ,
with one rule:
.hy 1
.RS 4
.RS 4
.PP
.EX
:msg, contains, \(dqiptables: \(dq -/var/log/iptables.log
.EE
.RE
.PP
See
.BR rsyslog (5)
and search for
.RI \(lq "Property-Based Filters" \(rq
for more information about filtering.
.RE
.TP
.B Using --log-prefix to add filter string
Make sure that all iptables log messages include the filter
string.  The easiest thing is to use the
.B --log-prefix \(dqiptables: \(dq
option for the
.B iptables
command.
.RS 4
.PP
If you prefer a different identifying tag, make sure that
the filter in the rsyslog.d file matches the --log-prefix
option value.
.PP
See
.BR iptables "(8) and " iptables-extensions (8)
for information about logging iptables actions.
.RE

