.TH sys_setup 7 2023-12-04
.SH NAME
.PP
.B sys_setup
- Universal steps for migrating to a new computer
.SH DESCRIPTION
.PP
It takes many steps to regain complete productivity in a new computer
when migrating from an mature computer whose working environment has
been configurd with deliberate and careful planning or with accidental
results following trial-and-error settings and package installations.
.PP
A new computer is a chance for a fresh start, to increase the ratio
of deliberate to accidental configurations.
.PP
The focus of this document is on
.BR Debian ,
a stable and minimal distribution.
.B Manjaro
was an experiment that mostly worked, but software updates often
disrupted my working environment, forcing me to waste precious hours
trying to restore my computer to working state.
.SH STEPS
.SS BUILD THE COMPUTER
.PP
This is obvious and won't be much discussed.
It is included for completeness.
.SS ENABLE SUDO
.PP
Installing software required
.I root
privileges, typically accessed through the
.B sudo
command.
.SS INSTALL FUNDAMENTAL SOFTWARE
.PP
At minimum, I need
.BR git ", "
.BR "C compiler" ", "
.BR Emacs ", "
.BR "offline documentation" ", and (maybe)"
.BR nfs-common .
.SS COPY IMPORTANT DATA FROM PREVIOUS COMPUTER
.PP
There will be many files in the old computer's
.B home
directory that should be copied to the new computer.
This starts with your email client, but includes any documents
you expect to be quickly available.

.SH INSTALLING IMPORTANT SOFTWARE
.TP
.B Update Apt Sources
Debian makes a distinction between free and non-free software, and
that ends up leaving out
.BR gcc(1) " and "  gdb(1) ,
among other things.
.IP
Use root (sudo) to open
.BR /etc/apt/sources.list .
I used a copy of the first line up to the
.I bookworm
argument to add two sources lines so they fit comfortable in
a man page.
.IP
.RS 11
.EX
deb http://deb.debian.org/debian/ bookworm contrib
deb http://deb.debian.org/debian/ bookworm non-free
.EE
.RE
.IP
Save the changes and update:

.RS 11
.EX
sudo apt-get update
.EE
.RE
.TP
.B Install Fundamental Software
As mentioned above, there are a few fundamental programs that you will
want available before going much further.
.IP
.EX
sudo apt-get install texinfo
sudo apt-get install git
sudo apt-get install emacs-nox
sudo apt-get install build-essential
sudo apt-get install gcc-doc gdb-doc
.EE
.TP
.B Color Styles
The commands have been installed for use, and comfortable use has
likely previously displayed colors for bold and italic in man and
info pages.
Below are a few applications that benefit from setting colors,
along with where the colors are set.
Consult or copy the corresponding files from the old computer to
set colors.
.RS 11
.TP
.B man (and less)
The colors for
.B less
are changed by means of environment variables starting with
.BR LESS_TERMCAP_ ,
usually found in the
.B ~/.bashrc
file.
.TP
.B Emacs
The colors in Emacs are usually set in the
.B ~/.emacs.d/init.el
configuration file.
.TP
.B info
This is not clearly defined, but creating or editing file
.BR ~/.infokey ,
a hidden file in the home directory defines many customizations,
among them are color-setting variables
.BR link-style ", " active-link-style ", and " match-style .
These do not style the bold and italic typefaces, but they do make
the info display more pleasing.
.IP
These settings are documented with an example in
.BI info " info"
main section \(dqColors and Styles\(dq.
.RE


.SH COPYING DATA FROM OLD COMPUTER
.PP
You will probably want to copy important data from the old computer
to your new computer.
In particular, the email client on the the computer should have your
saved emails for reference.
.PP
Some people advise using a flash drive to copy data from your old to
your new computer.
I think it is much easier to make a network connection, using
.B NFS
(network filesystem).
This will require both the host (the old computer) and the new
computer to be properly configured.
.SS ENABLE NFS ON BOTH COMPUTERS
.PP
On server only:
.EX
sudo apt-get install nfs-kernel-server
.EE

On both computers:
.EX
sudo apt-get install nfs-common
.EE
.SS ENABLE NFS-SERVER ON SOURCE COMPUTER
.PP
For security purposes, having
.B nfs-server
enabled should be a temporary state: you'll have to turn it on before
using it, then turning it off as soon as you're done:
.TP
.B Making the connection
The old computer is the source of data.  The following commands will
enable the new computer to connect before and disconnect and disable
.B nfs
immediately after copying data:
.EX
# Add \fB/home/chuck *(rw,sync,insecure)\fP to:
sudo emacs /etc/exports
sudo exportfs -rav
sudo systemctl enable --now nfs-server

# Target computer connect and copy data
# (see TARGET CONNECT AND COLLECT DATA below)

sudo systemctl nfs-server
# remove line \fB/home/chuck *(rw,sync,insecure)\fP from:
sudo emacs /etc/exports
.EE
.TP
.B Copying the data
.EX
tar zcf \fBsource\fP | ( cd \fBtarget\fP; tar xzfp - )
.EE

.SS TARGET CONNECT AND COLLECT DATA
.PP
Look at the following simple example of connecting, collecting data,
and disconnecting.
We first make an empty directory to which the mount will be attached.
Pick an appropriate directory and name for this.
It's probably not
.IR source .
.IP
.EX
mkdir source
sudo mount -t nfs target_id:/home/chuck ~/source -o async
cp source/.bashrc copied_bashrc
sudo umount source
.EE
.TP
.B Email, specifically Thunderbird
I have been using Thunderbird through multiple computers and I likely
will continue in order to keep old emails handy.
.IP
The Thunderbird configuration is found in hidden file
.BR ~/.thunderbird .
In that directory, among other files, there are two profile directories
with the extension
.BR default " or " default-default .
.IP
To migrate the email, we'll replace the empty profile
directories of the new computer with copies of the profile directories
in the old computer.
.IP
The file
.B ~/.thunderbird/profiles.ini of both computers configures the
profiles.
Make sure that you install the copies under the same
.IR [Profile1] " or " [Profile0]
sections in the new computer as they were installed in the old
computer.
.PP
Also make sure that
.B Default
variable in
.B ~/.thunderbird/installs.ini
is set to the same profile directory name as the value under the
.I [Profile0]
section of
.BR ~/.thunderbird/profiles.ini .
.PP
I used
.B tar
with the
.B z
option to compress the archive with
.BR gzip :
.IP
.EX
tar -czvf tbird_profiles.tar.gz .thunderbird/*.default*
cp tbird_profiles.tar.gz 
.EE



.SH SSH SETUPS
.PP
From non-password access to SSH servers for working and
.B scp
access, to
secure access to
.B https://www.github.com
and hosting services, preparation of SSH 


.SH ENABLE FINGERPRINT
.PP
If the fingerprint reader is reliable, using a fingerprint to login
and with
.B sudo
is a great convenience.
Configuration is not complicated, and consists of the following steps:
.TS
tab(|);
l lx.
install software|T{
.EX
apt install fprintd libpam-fprint
.EE
T}
enroll fingerprints CLI|T{
.EX
fprintd-enroll
.EE
T}
enroll fingerprints GUI|T{
Open
.B settings
app
.br
open
.B Users
.br
Use the
.B Fingerprint Login
T}
fingerprint with sudo|T{
.EX
pam-auth-update
.EE
T}

.TE
.SH CONFIGURE GIT
.TP
.B Name and email
.EX
git config --global --edit
.EE
.TP
.B Enable SSH access
Create your key with
.BR ssh-keygen ,
change directory to
.BR /~/.ssh ,
copy the contents of the .pub file to your copy buffer.
Then go to your https://www.github.com profile and add the key.
.IP
With the change, you will clone with an address like:
.IP
.RS 11
.EX
git clone git@github.com/cjungmann/manlinks.git
.EE
.RE
.SH DOWNLOAD AND INSTALL FONTS
.PP
If the standard collection of terminal fonts does not include one to
your liking, it is pretty easy to install new fonts.
.PP
We'll assume you can find and download True-Type fonts.
Once downloaded, go to directory
.BR /usr/share/fonts
and create a new directory named after the font you want to install.
Copy or move the font files you've download into the new font family
directory.
.PP
When the font files are properly resident under
.BR /usr/share/fonts ,
run the utility
.B fc-cache
to alert the computer to the existence of the new fonts.
.SH HOW TO INSTALL CERTAIN DOCUMENTATION FILES
.PP
Assuming that the
.B apt
system on the new computer will search for
.BR contrib " and " non-free
programs, you will be able to install several
.B info
manuals.
.IP
.EX
sudo apt-get install emacs-common-non-dfsg
sudo apt-get install gcc-doc
sudo apt-get install gdb-doc
sudo apt-get install bash-doc
sudo apt-get install tar-doc
sudo apt-get install glibc-doc
sudo apt-get install libncurses5-dev ncurses-doc
.EE
.PP
Refer to http://gnu.org/manual/manual.html for a very long list
of Gnu applications that might be useful to you.
