.TH quick_doxygen 7 "Miscellaneous Manual Page"
.ds D \fBDoxygen\fP
.SH NAME
.B quick_doxygen
\- Cheat sheet for basic Doxygen syntax
.SH DESCRIPTION
.PP
Just the basics for documenting functions and their arguments.
.SH SETUP
.PP
Before Doxygen can be used, it must be initialized and configured.
.TP 3
.BI doxygen " -g"
Initialize \D for the current directory.
.TP 3
.BI emacs " Doxyfile"
Search for and change the following settings:
.TS
tab(|);
l lx.
PROJECT_NAME|T{
Change this to your project name.
Don't be lame!
T}
EXTRACT_ALL = YES|T{
Set the value to
.I YES
to read all files as identified in
.BR FILE_PATTERNS .
T}
RECURSIVE = YES|T{
Especially if your project puts source files in subdirectories,
set this tag to
.B YES
to enable searching subdirectories for files.
T}
OPTIMIZE_OUTPUT_FOR_C = YES|T{
(Example) Consider setting an optimize flag for your primary source language.
T}
.TE

.SH EXAMPLE
.PP
Let's just use examples to illustrate usage:
.SS Function Documentation
.PP
.EX
/**
 * @brief Short description of function
 *
 * Unmarked text in a Doxygen comment block will be used for the
 * detailed function description.
 *
 * The detailed description can span several lines or paragraphs.
 *
 * @param result [in,out] Allocated char* returned through this parameter
 * @param Arg1 [in]       Integer argument for the function
 * @param Arg2 [in]       String argument for the function
 * @param Arg3 [in]       Struct argument for the function.  The argument
 *                        description can span multiple lines.
 *
 * @return The exit value is 0 for success, or an error code
 *         for failure.  Refer to errno(1) for values.
 */
int my_function(chat **result, int Arg1, const char *Arg2, struct myobj Arg3)
{
.EE
.SS Enum Documentation
.PP
An enumeration may document the set of allowed values for an
integer parameter or return value.
There is a Doxygen syntax for documenting enums.
.PP
.EX
/** This enum class is da bomb! */
enum int dabomb {
   cap,          ///< smallest explosive
   bang_snap,    ///< once a particular favorite of kids in grade school
   firecracker,  ///< can seriously injure someone if used carelessly
   cherry_bomb,  ///< once more dangerous than a firecracker
   dynamite,     ///< criminals and miners love it
   hand_grenade, ///< used in war
   land_mine,    ///< buried explosive
   missle,       ///< self-propelled lethal explosive
   bomb,         ///< big booms
   nuke          ///< the biggest boom
};
.EE
.SS CROSS-REFERENCES
.PP
Use the
.BR \(rsref " (" @ref )
command to call highlight and link to objects that are defined
elsewehere in the project:
.RS 4
.B \(rsref
.IR reference " [" \(dqlabel\(dq ]
.RE
.PP
If a
.I label
argument is included, it will replace the reference name in the same manner
as an HTML anchor object.
.B Doxygen
tries to be intellegent about which words are appropriate or not as labels.
Enclosing with quotes the text you want to serve as a label makes it clear
and overrides other considerations.
.PP
For example:
.RS 4
.EX
Look at \(rsref MyStruct::member \(dqmember of MyStruct\(dq for more info.
.EE
.RE
.SS WORD MARKUP
.PP
.B Doxygen
includes several several commands that style the following word.
An HTML coder might be tempted to use them in service of \(lqsemantic\(rq
markup.
.PP
I recommend using
.B Markdown
syntax (surrounding words with
.BR _ ", " * ", or " ` )
instead for ease of reading in the source code.
.PP
If you insist on using
.B Doxygen
syntax, the following commands generate italic, bold, or monospaced text:
.TS
tab(|);
l l l.
\(rsa|emphasis|italic
\(rsb|strong|bold
\(rsc|code|monospace (typewriter)
\(rse|emphasis|italic
\(rsp|parameter|monospace
.TE
.SS HIDE CODE FROM DOXYGEN
.PP
Sometimes it is not appropriate to include certain blocks of
code in the documentation.
For these sections, create a comment block with
.B @cond
before the section starts, and a comment block with
.B @endcode
after the end.
For example,
.IP
.EX
// Hide debugging code from Doxygen
.B /** @cond */
#ifdef INCLUDE_MAIN

void test(void) { do_it(); }

int main(int argc, const char **argv)
{
   test();
}

#endif
.B /** @endcond */
.EE

.SS WRITING AMBIGUOUS CHARACTERS
.PP
There are several characters or character combinations that may be
misinterpreted in certain situations.  They should be escaped with a
leading backslash (\(rs).  In particular,
.BR < ", " > ", and " &
may be taken to be part of an HTML tag.
The following link to the official
.B Doxygen
site lists these tricky characters.
.PP
.UR https://www.doxygen.nl/manual/commands.html#cmdamp
Doxygen Commands Page
.UE
.SS SEE ALSO
.PP
This document will likely never be complete.
The following links will take you to other resources that may
aid your quest for further understanding:
.PP
.nf
.UR http://opensource.com/sites/default/files/2022-05/OSDC_cheatsheet-doxygen-2022.5.30.pdf
Open Source cheatsheet
.UE
.fi
