.TH quick_emacs 7 "Miscellaneous Information Manual"
.ds em \fBEmacs\fP
.de KEYP
.  B \\$1\c
.  shift
.  while \\n[.$] \{\
.  RB ", " "\\$1"\c
.  shift
.  \}
..
.de KEYBI
.  B \\$1
.  I \\$2
..
.SH NAME
.B quick_emacs
\- A quick guide to basic \*(em commands.
.SH DESCRIPTION
Terminal-available cheatsheet for \*(em.
.SH RESEARCH TOPICS
.PP
There are some things I'd like to do in \*(em that I'm
not sure how to do just now.
The following list is a reminder to look into these ideas,
either solve them or delete them.
.TP
.B Show Variables
I'd like to see a list of all currently active variables.
That would help decipher certain settings.
.SH CHEATSHEET
.SS STARTING AND EXITING EMACS
.TS
tab(|);
l lx .
T{
.KEYP "C-x C-c"
T}|Exit \*(em
T{
.KEYP "C-x C-f"
T}|Open file for editing
T{
.KEYP "C-x C-r"
T}|Open file for viewing (read-only)
T{
.KEYP "C-x C-s"
T}|Save current buffer
T{
.KEYP "C-x C-k"
T}|Kill (close) current buffer
.TE
.SS MOVING AROUND
.TS
tab(|);
l lx .
T{
.KEYP C-f C-b
T}|Move forward, backward one character
T{
.KEYP M-f M-b
T}|Move forward, backward one word
T{
.KEYP C-p C-n
T}|Move up one line, down one line
T{
.KEYP M-v
T}|Move up a screenful
T{
.KEYP C-v
T}|Move down a screenful
T{
.KEYP M-< M->
T}|Move to top, bottom of document
.TE
.SS UNDO
.TS
tab(|);
l lx .
T{
.KEYP "C-x u"
T}|Undo edits, most recent first
T{
.KEYP "C-g"
T}|Cancel unexecuted or incomplete command
.TE
.SS CUT, COPY, AND PASTE
.TS
tab(|);
cB s
l lx .
Yank (otherwise known as Paste)
T{
.KEYP C-y
T}|Insert kill-ring content at cursor
.T&
cB s
l lx .
Direct Content Cut and Copy
T{
.KEYP Backspace
T}|Move cursor left, deleting character under new position
T{
.KEYP DEL
T}|Delete character under the cursor
T{
.KEYP C-DEL
T}|Save and delete from cursor to end-of-word
T{
.KEYP C-k
T}|Save and delete from cursor to end-of-line
.T&
cB s
l lx .
Region-oriented
T{
.KEYP C-space
T}|T{
Mark an end of a new region, move the cursor to enlarge selection area.
T}
T{
.KEYP C-w
T}|Save and delete region
T{
.KEYP M-w
T}|Save and preserve region
T{
.KEYP Backspace
T}|Delete region without adding to kill-ring
.TE
.SS SEARCH AND REPLACE
.TS
tab(|);
l lx .
T{
.KEYP C-s
T}|Search for string
T{
.KEYP C-M-s
T}|Search for regex pattern
T{
.KEYP M-%
T}|Interactive search and replace
T{
.KEYP C-M-%
T}|T{
Interactive search and replace using regex patterns.
T}
T{
.KEYP C-x\ replace-string
T}|Unprompted replace-string
T{
.KEYP C-x\ replace-query
T}|Unprompted replace regex matches, including captures
.TE
.\"" PAGE BREAK HERE or SPLIT SCREEN table gets broken
.bp
.\""
.SS SPLIT SCREEN
.TS
tab(|);
l lx .
T{
.KEYP "C-x 0"
T}|Remove active pane from display
T{
.KEYP "C-x 1"
T}|Remove all panes except active pane
T{
.KEYP "C-x 2"
T}|Split screen top-by-bottom
T{
.KEYP "C-x 3"
T}|Split screen side-by-side
T{
.KEYP "C-x o"
T}|Switch to next pane
.TE
.SS RECTANGLES
.PP
We assume you know how to define a rectangle.
Learn about rectangles in the \*(em info page.
.TS
tab(|);
l lx .
T{
.KEYP "C-x r k"
T}|T{
Kill (delete) rectangle.  Remove rectangle contents and close space from right.
T}
T{
.KEYP "C-x r o"
T}|T{
Open rectangle area of spaces by shifting existing content right
T}
T{
.KEYP "C-x r y"
T}|Yank rectangle
T{
.KEYP "C-x r c"
T}|Cut rectangle area out without closing space from right.
.TE
.SS MACROS
.TS
tab(|);
l lx .
T{
.KEYP F3 "C-x ("
T}|Start recording a macro
T{
.KEYP F4 "C-x )"
T}|End a macro recording
T{
.KEYP F4 "C-x e"
T}|Run last-defined macro
T{
.KEYP "C-x C-k n"
T}|Assign a name to the last-defined macro.
T{
.KEYP "C-x C-k b"
T}|Assign key sequence to the last-defined macro.
T{
.KEYP "C-x C-k SPC"
T}|Begin macro editing/debugging moode.
T{
.KEYBI "M-x " "macro_name"
T}|Run named macro (if \fImacro_name\fP is valid Lisp symbol).
.TE
.SS CUSTOMIZATION
.PP
Change syntax-highlighting colors to your work style.
Use
.B describe-face
to identify the face, then use
.B list-faces-display
to find the face and change the color.
.TS
tab(|);
l lx .
T{
.BI M-x " describe-face " RET
T}|Identify the face of the text under the cursor.
T{
.B "C-u" " C-x " "="
T}|Same as \fIdescribe-face\fP
T{
.KEYBI "M-x" list-faces-display
T}|T{
Display (for editing) faces and color for syntax face names.
T}
T{
.KEYBI "M-x" customize
T}|Comprehensive customization dialog
.TE
.SS MISCELLANEOUS
.TS
tab(|);
l lx .
T{
.KEYP "C-x C-q"
T}|Toggle read-only mode.
T{
.KEYP M-x\ revert
T}|Reload file from disk (abandoning changes)
T{
.KEYP "C-h m"
T}|Get information on current mode and submodes.
.TE
.SS FUTURE STUFF
.PP
The following are some \*(em features that I don't currently
use but may want to explore in the future.
.TP
.B Registers
Registers can be used to save positions, text, rectangles,
window configurations, numbers, file names, and keyboard macros.
.TP
.B Spell Check
The macros exist, but a database must be setup.
If I need to use it, I'll figure it out and document it.
