.TH quick_xslt 7 "Miscellaneous Information Manual"
.SH NAME
.B quick_xslt
\- Grossly inadequate guide to XSLT
.SH DESCRIPTION
.PP
An extremely humble beginning of a cheatsheet while I try to
recall XSLT coding from several years ago.
The purpose of this document is to record tiny concepts and techinques
that I recall or rediscover on the way to developing a new XSLT
stylesheet for parsing Doxygen XML output.
.SH TRIVIA
.PP
This will be haphazard until I collect enough information that it
make sense to organize it.

.SH USEFUL VARIABLES
.TS
tab(|);
lx l.
<xsl:variable name=\(dqnl\(dq select\(dq\(aq&#10;\(aq\(dq />|newline character
.TE

.SH USEFUL FUNCTIONS
.PP
The page,
.UR https://www.w3schools.com/xml/xsl_functions.asp
.UE ,
documents many functions.
The following list is a subset of the ones I find most useful.
.TS
tab(|);
l lx .
concat(string, string, ...)|T{
concatenate strings in the argument list.
T}
string-length(string)|T{
returns length of string
T}
substring(string,start,len)|T{
returns substring of string.  len can be omitted.
T}
normalize-space(string)|T{
remove leading, trailing spaces, replaces all spaces-strings with a single space
T}
upper-case(string)|T{
returns string with lower case characters translated to upper-case.
T}
lower-case(string)|T{
returns string with upper case characters translated to lower-case.
T}
translate(target,select,replacements)|T{
Translate target by replacing letters in select with a letter at the same offset in replacements
T}
escape-uri(string, esc-res)|T{
Look this one up yourself
T}
contains(target, pattern)|T{
True if pattern in target string
T}
starts-with(target, pattern)|T{
True if target string starts with pattern string
T}
ends-with(target, pattern)|T{
True if target string ends with pattern string
T}
matches(target, pattern)|T{
True if pattern found in target
T}
replace(target, pattern, replace)|T{
Replaces pattern matches in target with contents of replace
T}
.TE

