.TH quick_regex 7 "Miscellaneous Information Manual"
.SH NAME
.B quick_regex
-/ Guide to escaping regular expression characters
.SH DESCRIPTION
.PP
This document is for people who understand the difference between
regular and meta characters in a regular expression but may have
trouble remembering when to escape meta or normal characters in a
given context.
.SH META-CHARACTERS
.PP
Meta-characters are typeable characters that may have a special meaning
in a regular expression.
Depending on the context, sometimes the characters are escaped to be
meta-characters, in other contexts the characters are escaped to match
themselves.
.TS
tab(|);
c l lx.
Character|Name|Meaning
_
\&.|dot|match any character|
\(ba|infix|separate equivalent matches
(|parenthesis|begin group expression
)|parenthesis|end group expression
{|brace|begin repetition expression
?|question|match preceding expression zero or one times
*|star|match preceding expression zero or more times
+|plus|match preceding expression one or more times
^|caret|match the start of a line or string
$|dollar|match the end of a line or string
.TE
.SH REGEX DIALECTS
.SS Basic Regular Expressions (BRE)
Characters that want to serve as meta-characters must be escaped with a
preceeding backslash.
.IP
For example,
.br
.BR ( " matches a literal parenthesis, and " \(rs( " introduces a group."
.br
.BR . " matches a literal period/dot, and " \(rs. " is a wildcard."
.SS Extended Regular Expressions (ERE)
.PP
By default, meta-characters take their meta meaning, and will match
the literal character if it is escaped in the expression.
.IP
For example,
.br
.BR ( " introduces a group, and " \(rs( " matches a literal left-parentheis."
.br
.BR . " is a wildcard, and " \(rs. " matches a literal period/dot."
.SS Perl-compatible Regular Expressions (PCRE)
.PP
PCRE is more expressive and powerful, and thus more complicated.
Basically, meta-characters in PCRE are similar to ERE, where the
meta-meaning is the default, and the meta-character must be escaped
to match a literal of the matching character.
.PP
See
.BR pcrepattern (3)
for a complete explanation of PCRE regular expressions.
