.TH gitcs 7 "25 April 2022" "Version 0"
.SH NAME
gitcs \- git Cheat Sheet
.SH DESCRIPTION
There are so many features in
.B git
that it can be very hard to remember how to do basic things.  This
unofficial
.B man
page is my growing personal list of
.BR git cheats.

.SH SEARCHS

.P
Repository search for function:
.RS 4
.B git log -S\fIfunction_name
.RE

.P
Show files under git control:
.RS 4
.B git ls-files
.RE

