.TH less_termcaps 7 2022-05-06
.SH NAME
.B less_termcap
\(em suffix meanings
.SH EXAMPLES
This page shows the meanings of the several
.B LESS_TERMCAP_xx
environment variables.

.TS
l l l
---
l l l .
Variable	Meaning	Mnemonic
LESS_TERMCAP_ks	keypad sends command	T{
.BR k eypad " s" end
T}
LESS_TERMCAP_ke	keypad end sending command	T{
.BR k eypad " e" "nd sending data"
T}
LESS_TERMCAP_vb	send visual bell	T{
.BR v isual " b" ell
T}
LESS_TERMCAP_mb	start blink	T{
.BR m ake " b" link
T}
LESS_TERMCAP_md	start bold	T{
.BR m ake " d" ouble(?!)
T}
LESS_TERMCAP_me	end bold, blink, italic	T{
.BR m odifications " e" nd
T}
LESS_TERMCAP_so	start stand-out	T{
.BR s tand "-o" ut
T}
LESS_TERMCAP_se	end stand-out	T{
.BR s tand-out " e" nd
T}
LESS_TERMCAP_us	start underline/italic	T{
.BR u nderline " s" tart
T}
LESS_TERMCAP_eu	end underline/italic	T{
.BR e nd " u" nderline
T}
.TE

